<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [
        <!ELEMENT root (header,body)>

        <!ELEMENT header (from,to)>
        <!ELEMENT to      (#PCDATA)>
        <!ELEMENT from    (#PCDATA)>

        <!ELEMENT body (user,passWord)>
        <!ELEMENT user    (#PCDATA)>
        <!ELEMENT passWord    (#PCDATA)>

        <!ENTITY pw "123">
        ]>
<root>
    <header>
        <from></from>
        <to></to>
    </header>
    <body>
        <user></user>
        <passWord>&pw;</passWord>
    </body>
</root>


